matching/config/routes.rb
Rails.application.routes.draw do
  resources :block_lists
  resources :date_schedules
  resources :meet_requests
  root to: 'sessions#new'
  get 'messages/check'
  post 'messages/set_receive'
  get 'messages/set_receive'
  resources :messages
  get 'sessions/new'
  get 'match_requests/target_user_list'
  get 'users/:id/profile' => 'users#profile'
  resources :match_requests
  resources :users
  # post 'chat' => 'messages#index'
  post 'messages/index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy' #deleteの場合はmethod: :deleteが必要
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

matching/app/models/match_request.rb
class MatchRequest < ApplicationRecord
belongs_to :request_user, :class_name => User
belongs_to :target_user, :class_name => User
end

matching/app/controllers/match_requests_controller.rb
class MatchRequestsController < ApplicationController
  before_action :set_match_request, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:profile,:show, :edit, :update, :destroy,:index]

  def target_user_list
    @current_user = User.find_by(id: session[:user_id]) #自分
    @receive_user = User.find_by(id: session[:user_id])
    #送信者が自分のリクエストのターゲットユーザのリスト(自分がリクエストを送った人)
    requested = MatchRequest.where(request_user_id: @current_user.id).pluck(:target_user_id)
    block = BlockList.where(blocked_by:@current_user.id).pluck(:blocked)
    @users = User.where("id != ?",@current_user.id).where.not(id: requested).where.not(id:block).paginate(:page => params[:page], :per_page => 12) #自分/blockしてる以外
  end

  # GET /match_requests
  # GET /match_requests.json
  def index
    @match_requests = MatchRequest.all
  end

  # GET /match_requests/1
  # GET /match_requests/1.json
  def show
  end

  # GET /match_requests/new
  def new
    @match_request = MatchRequest.new
  end

  # GET /match_requests/1/edit
  def edit
  end

  # POST /match_requests
  # POST /match_requests.json
  def create
    @match_request = MatchRequest.new(match_request_params)
    if @match_request.save
      redirect_to action: 'target_user_list', notice: 'リクエストを送信しました。'
    else
      render :new, notice: 'リクエスト送信エラー'
    end
    # respond_to do |format|
      # if @match_request.save
      #   format.html { redirect_to action: 'target_user_list',notice: 'Match request was successfully created.'}
      #   format.json { render :show, status: :created, location: @match_request }
      # else
      #   format.html { render :new }
      #   format.json { render json: @match_request.errors, status: :unprocessable_entity }
      # end
    # end
  end

  # PATCH/PUT /match_requests/1
  # PATCH/PUT /match_requests/1.json
  def update
    respond_to do |format|
      if @match_request.update(match_request_params)
        format.html { redirect_to @match_request, notice: 'Match request was successfully updated.' }
        format.json { render :show, status: :ok, location: @match_request }
      else
        format.html { render :edit }
        format.json { render json: @match_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /match_requests/1
  # DELETE /match_requests/1.json
  def destroy
    @current_user = User.find_by(id:session[:user_id])
    if @match_request.destroy
      BlockList.create(blocked_by:@match_request.request_user_id,blocked:@match_request.target_user_id)
      Message.where(send_user_id:@match_request.request_user_id, receive_user_id:@match_request.target_user_id).destroy_all
      Message.where(send_user_id:@match_request.target_user_id, receive_user_id:@match_request.request_user_id).destroy_all
      redirect_to controller: "match_requests", action:"target_user_list", notice:"マッチを解除しました"
    end
    # respond_to do |format|
    #   format.html { redirect_to match_requests_url, notice: 'Match request was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match_request
      @match_request = MatchRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_request_params
      params.require(:match_request).permit(:request_user_id, :integer, :target_user_id, :integer)
    end
    def login_check
      if session[:user_id] == nil
        redirect_to controller:'sessions',action:'new', notice:'ログインしてください'
      end
    end
end

matching/app/helpers/match_requests_helper.rb
module MatchRequestsHelper
end

matching/app/views/match_requests/_form.html.erb
<%= form_with(model: match_request, local: true) do |form| %>
  <% if match_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match_request.errors.count, "error") %> prohibited this match_request from being saved:</h2>

      <ul>
      <% match_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :request_user_id %>
    <%= form.text_field :request_user_id, id: :match_request_request_user_id %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer, id: :match_request_integer %>
  </div>

  <div class="field">
    <%= form.label :target_user_id %>
    <%= form.text_field :target_user_id, id: :match_request_target_user_id %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer, id: :match_request_integer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

matching/app/views/match_requests/edit.html.erb
<h1>Editing Match Request</h1>

<%= render 'form', match_request: @match_request %>

<%= link_to 'Show', @match_request %> |
<%= link_to 'Back', match_requests_path %>

matching/app/views/match_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Match Requests</h1>

<table>
  <thead>
    <tr>
      <th>Request user</th>
      <th>Integer</th>
      <th>Target user</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @match_requests.each do |match_request| %>
      <tr>
        <td><%= match_request.request_user_id %></td>
        <td><%= match_request.integer %></td>
        <td><%= match_request.target_user_id %></td>
        <td><%= match_request.integer %></td>
        <td><%= link_to 'Show', match_request %></td>
        <td><%= link_to 'Edit', edit_match_request_path(match_request) %></td>
        <td><%= link_to 'Destroy', match_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match Request', new_match_request_path %>

matching/app/views/match_requests/new.html.erb
<h1>New Match Request</h1>

<%= render 'form', match_request: @match_request %>

<%= link_to 'Back', match_requests_path %>

matching/app/views/match_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Request user:</strong>
  <%= @match_request.request_user_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @match_request.integer %>
</p>

<p>
  <strong>Target user:</strong>
  <%= @match_request.target_user_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @match_request.integer %>
</p>

<%= link_to 'Edit', edit_match_request_path(@match_request) %> |
<%= link_to 'Back', match_requests_path %>

matching/app/views/match_requests/target_user_list.html.erb
<h1></h1>
<% if params[:notice] %>
  <div class="alert alert-success" role="alert"><%= params[:notice] %></div>
<% end %>
<div class="container">

  <div class = "row">
    <% @users.each do |user| %>
    <div class="col-3">
        <div class="targets" align="center">
          <%= form_for(MatchRequest.new) do |form| %>
            <%= link_to image_tag(user.image, class: "rounded-circle", size:"150x150", style:"border:2px solid white;"), controller: :users, action: :profile,id: user%>
              <h5><%= link_to user.name, controller: :users, action: :profile,id: user %></h5>
              <p>
                <% if user.prof.length > 0 %>
                  <p class="comment" align="left"><%= user.prof.truncate(15)%></p>
                <% else %>
                  <p class="comment" align="left" style="color:silver;">no profile</p>
                <% end %>
              </p>
              <%= form.hidden_field :request_user_id, :value => @current_user.id%>
              <%= form.hidden_field :target_user_id, :value => user.id%>
              <%= button_tag type: :submit, class:"btn-good" do %>
                <%= image_tag "good_white.svg",size:"20x20"%>
                いいね！
              <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= will_paginate @users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer,:previous_label=>'前', :next_label=>'次', class:"navbar-center"%>
</div>