matching/config/routes.rb
Rails.application.routes.draw do
  resources :block_lists
  resources :date_schedules
  resources :meet_requests
  root to: 'sessions#new'
  get 'messages/check'
  post 'messages/set_receive'
  get 'messages/set_receive'
  resources :messages
  get 'sessions/new'
  get 'match_requests/target_user_list'
  get 'users/:id/profile' => 'users#profile'
  resources :match_requests
  resources :users
  # post 'chat' => 'messages#index'
  post 'messages/index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy' #deleteの場合はmethod: :deleteが必要
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

matching/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matching</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!-- トークルームを選択していない時にエラーにならないように -->
  <% if @receive_user == nil %>
    <% @receive_user = User.find_by(id: session[:user_id])%>
  <% end %>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light nav_top">
      <a class="navbar-brand">
        <%= image_tag "papillon_yellow.svg", width: "30", height: "30",class:"d-inline-block align-top",alt:"" %>
          Papillon
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <% if @current_user %>
            <ul class="navbar-nav mr-auto active">
              <!-- <%= link_to 'メッセージ', user_path(@current_user), class: "nav-item nav-link", style:"color:#FFC400;" %> -->
              <%= link_to 'マッチを探す', match_requests_target_user_list_path, class: "nav-item nav-link", style:"color:#FFC400;"%>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:#FFC400;">
                  設定
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to 'プロフィールを編集', edit_user_path(id:@current_user), class: "dropdown-item" %>
                  <a class="dropdown-item" href="#">お問い合わせ</a>
                  <a class="dropdown-item" href="#">良縁報告</a>
                </div>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', logout_path, method: :delete, class: "nave-item nav-link", style:"color:#FFC400;"%>
              </li>
            </ul>

              <span class="navbar-text" style="color:#FFC400;"><%=@current_user.name%>でログイン中</span>
          <% else %>
            <ul class="navbar-nav mr-auto">
            </ul>

              <form class="form-inline">
                <%= link_to '新規登録', new_user_path, class: "btn btn-outline-success" %>
              </form>
          <% end %>
        </div>
      </div>
    </nav>

    <% if @current_user %>

      <div class="container-fluid">
        <div class="row">
           <div class="col-4" style="padding-top:3%; width:120%; background-color:white;">
            <table style="width:100%">
              <% @current_user.matchers.each do |matcher| %>
                <tr class="<%= "highlight" if matcher.id == @receive_user.id %>">
                  <th><%= link_to image_tag(matcher.image,class:'rounded-circle',size:"40x40"), controller: :users, action: :profile, id:matcher %></th>
                  <% newest_message = Message.where(send_user_id:@current_user,receive_user_id:matcher).or(Message.where(send_user_id:matcher,receive_user_id:@current_user)).last%>
                  <td>
                    <%= matcher.name %>
                    <% if newest_message%>
                    <%= link_to newest_message.body.truncate(20), messages_set_receive_path(receive_id:matcher.id),method: :post,style:"display:block; width:100%; height:100%; padding:10px; color:#c0c0c0; text-decoration: none;"%>
                    <% else %>
                      <%= link_to ' ', messages_path(receive_id: matcher.id, send_id: @current_user.id), style:"display:block; width:100%; height:100%; padding:10px; color:#c0c0c0; text-decoration: none;"%>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
          <div class="col-8" style="padding-top:3%;">
            <div id="ad-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">

              <!-- 実際の画像の表示処理 -->
              <div class="carousel-inner">
                <div class="carousel-item active">    <!-- activeをつけたものがページ表示時に表示される -->
                  <%= image_tag 'banner1.png', class: "d-block w-100", alt:"First slide"%>
                </div>
                <div class="carousel-item">
                  <%= image_tag 'banner2.png', class: "d-block w-100", alt:"Second slide"%>
                </div>
                <div class="carousel-item">
                  <%= image_tag 'banner3.png', class: "d-block w-100", alt:"Third slide"%>
                </div>
              </div>

              <!-- 前の画像へ戻るための矢印ポインタ -->
              <a class="carousel-control-prev" href="#ad-carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#ad-carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
            <%= yield%>
          </div>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

  </body>
</html>