matching/config/routes.rb
Rails.application.routes.draw do
  resources :block_lists
  resources :date_schedules
  resources :meet_requests
  root to: 'sessions#new'
  get 'messages/check'
  post 'messages/set_receive'
  get 'messages/set_receive'
  resources :messages
  get 'sessions/new'
  get 'match_requests/target_user_list'
  get 'users/:id/profile' => 'users#profile'
  resources :match_requests
  resources :users
  # post 'chat' => 'messages#index'
  post 'messages/index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy' #deleteの場合はmethod: :deleteが必要
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

matching/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :send_user, :class_name => User
  belongs_to :receive_user, :class_name => User

  def self.talk(receive_id,send_id)
    if receive_id
      Message.where(send_user_id: send_id, receive_user_id: receive_id).or(Message.where(send_user_id: receive_id, receive_user_id: send_id))
    else
      Message.all
    end
  end

end

matching/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:show, :edit, :update, :destroy,:index]
# アクセスできない
  def check
    @messages = Message.all
  end

  # GET /messages
  # GET /messages.json
  def set_receive
    session[:receive_id] = params[:receive_id]
    redirect_to action: "index"
  end
  def index
    # session[:receive_id]=params[:receive_id]
    @current_user = User.find_by(id: session[:user_id])
    # if params[:receive_id] == nil
    #   params[:receive_id] == @current_user.id
    # end
    # @messages = Message.talk(params[:receive_id], @current_user.id)
    # @receive_user = User.find(params[:receive_id])
    # @meet = MeetRequest.exists?(meet_request_user_id: @current_user.id, meet_target_user_id: params[:receive_id])&& MeetRequest.exists?(meet_request_user_id: params[:receive_id], meet_target_user_id: @current_user.id)
    @messages = Message.talk(session[:receive_id], @current_user.id)
    @receive_user = User.find(session[:receive_id])
    @meet = MeetRequest.exists?(meet_request_user_id: @current_user.id, meet_target_user_id: @receive_user.id)&& MeetRequest.exists?(meet_request_user_id: @receive_user.id, meet_target_user_id: @current_user.id)

    @sug_schedules = DateSchedule.where(date_sug_user_id: @current_user.id,date_tar_user_id: @receive_user.id)
    @sugged_schedules = DateSchedule.where(date_sug_user_id: @receive_user.id,date_tar_user_id: @current_user.id)
    @match_to = MatchRequest.find_by(request_user_id:@current_user.id,target_user_id:@receive_user.id)
    @match_from = MatchRequest.find_by(request_user_id:@receive_user.id,target_user_id:@current_user.id)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.save
    @receive_user = User.find(@message.receive_user_id)
    session[:receive_id] = @message.receive_user_id
    redirect_to action: "index"
    # redirect_to action: "index",:receive_id => @message.receive_user_id

#    respond_to do |format|
  #      #format.html { redirect_to @message, notice: 'Message was successfully created.' }
  #      #format.json { render :show, status: :created, location: @message }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @message.errors, status: :unprocessable_entity }
  #    end
  #  end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :send_user_id, :receive_user_id)
    end
    def login_check
      if session[:user_id] == nil
        redirect_to controller:'sessions',action:'new', notice:'ログインしてください'
      end
    end
end

matching/app/helpers/messages_helper.rb
module MessagesHelper
end

matching/app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :message_body %>
  </div>

  <div class="field">
    <%= form.label :send_user_id %>
    <%= form.number_field :send_user_id, id: :message_send_user_id %>
  </div>

  <div class="field">
    <%= form.label :receive_user_id %>
    <%= form.number_field :receive_user_id, id: :message_receive_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

matching/app/views/messages/check.html.erb
<% @messages.each do |message| %>
  <%= message.body %>
  <%= message.created_at %>
<% end %>

matching/app/views/messages/data_check.html.erb
<% @messages.each do |message| %>
  <%= message.body %>
  <%= message.created_at %>
<% end %>

matching/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

matching/app/views/messages/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="sample">
<% if params[:notice] %>
  <div class="alert alert-success" role="alert"><%= params[:notice] %></div>
<% end %>
<div class="container-fluid" style="padding:2%;">
<div class="row">
  <div class="col-8"  style="background-image:url(<%= asset_path "talk_back.png" %>);border-radius:3px;border:3px solid black;">
    <%= form_with model: Message.new do |form| %>
      <div class="field">
        <%= form.hidden_field :send_user_id, :value => @current_user.id %>
        <%= form.hidden_field :receive_user_id, :value => @receive_user.id %>
      </div>
      <div class="input-group mb-3">
        <% form.label :body %>
        <%= form.text_field :body, id: :message_body, class: "form-control", placeholder: "メッセージ" %>
        <div class="input-group-append">
          <%= form.submit "送信",class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    <div class="box_srcollbar">
      <% if @messages %>
        <% @messages.reverse_each do |message| %>
            <div class="comment_area">
              <div ng-repeat="data in hoge.chatdata">
                <div class="row">
                  <div class="col-md-12">
                    <% if message.send_user_id == @current_user.id %>
                      <div class="pull-right">
                        <%= image_tag @current_user.image, :size => "25x25" ,class: "rounded-circle" %>
                        <%= @current_user.name %>
                      </div>
                      <p class="right_balloon"><%= message.body %></p>
                    <% else message.receive_user_id == @current_user.id %>
                      <span ng-if="data.type == 'chat'">
                        <div class="pull-left">
                          <%= link_to image_tag(@receive_user.image, class: "rounded-circle", size:"25x25"), controller: :users, action: :profile, id:@receive_user%>
                          <%= @receive_user.name %>
                        </div>
                        <p class="left_balloon"><%= message.body %></p>
                      </span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-4">
    <div class="box">
    <p align="center">会いたい！ボタン</p>
    <%= form_for(MeetRequest.new,url: meet_requests_url) do |form|%>
      <%= form.hidden_field :meet_request_user_id, :value => @current_user.id %>
      <%= form.hidden_field :meet_target_user_id, :value => @receive_user.id %>
      <% if MeetRequest.exists?(meet_request_user_id: @current_user.id, meet_target_user_id: @receive_user.id) %>
        <a class="btn btn-success btn-block disabled" role="button">送信済</a>
      <% else %>
        <%= form.submit '会いたい！', class: "btn btn-block btn-success"%>
      <% end %>
    <% end %>

    <% if @meet %>
      <div align="center">お互いに会いたいようです。<br>日程調整をしましょう。</div>

      <!-- 部分テンプレート化できる -->
      <%= form_for(DateSchedule.new) do |form|%>
        <%= form.hidden_field :date_sug_user_id, :value => @current_user.id%>
        <%= form.hidden_field :date_tar_user_id, :value => @receive_user.id%>
        <div class="input-group mb-3">
          <%= form.text_field :date_of_meet, id: :date_schedule_date_of_meet ,class: 'date-picker form-control'%>
          <div class="input-group-append">
            <%= form.submit '提案する', class: "btn btn-primary"%>
          </div>
        </div>
      <% end %>
      <!-- 部分テンプレート化できる -->

      <strong>提案した予定</strong><br>
      <% if @sug_schedules.where(confirm:false).exists? %>
        <% @sug_schedules.where(confirm:false).reverse_each do |sug_schedule|%>
          <%= sug_schedule.date_of_meet.strftime("%Y年%m月%d日")%>
          <%= link_to '取消', date_schedule_path(sug_schedule.id), method: :delete,class:"btn btn-block btn-success"%><br>
        <% end %>
      <% else %>
        <p style="color:darkgray;">提案した予定はありません。</p>
      <% end %>

      <strong>提案された予定</strong><br>
      <% if @sugged_schedules.where(confirm:false).exists? %>
        <% @sugged_schedules.where(confirm:false).reverse_each do |sugged_schedule|%>
          <%= sugged_schedule.date_of_meet.strftime("%Y年%m月%d日")%><br>
          <%= form_for(DateSchedule.find_by(id:sugged_schedule.id)) do |form|%>
            <%= form.hidden_field :confirm, :value => true %>
            <%= form.submit "確定", class:"btn btn-block btn-primary" %>
          <% end %>
        <% end %>
      <% else %>
        <p style="color:darkgray;">提案された予定はありません。</p>
      <% end %>

      <strong>確定した予定</strong><br>
      <% if @sug_schedules.where(confirm:true).exists? %>
        <% @sug_schedules.where(confirm:true).reverse_each do |schedule|%>
          <%= schedule.date_of_meet.strftime("%Y年%m月%d日")%><br>
        <% end %>
      <% end %>
      <% if @sugged_schedules.where(confirm:true).exists? %>
        <% @sugged_schedules.reverse_each do |schedule|%>
          <%= schedule.date_of_meet.strftime("%Y年%m月%d日")%><br>
        <% end %>
      <% end %>
      <% if @sug_schedules.where(confirm:true).exists? || @sugged_schedules.where(confirm:true).exists? %>
      <% else %>
        <p style="color:darkgray;">提案された予定はありません。</p>
      <% end %>

    <% end %>
  </div>
  <br>
  <%= link_to 'マッチを解除', match_request_path(@match_to.id), method: :delete,class:"btn btn-block btn-success",data:{confirm: 'マッチを解除してよろしいですか？'} %><br>
  </div>
</div>
</div>
<!-- <nav class="navbar fixed-bottom navbar-light" style="background-color: #120A4A; color:#ffa500;">
    <div class="navbar-center">
        <%= link_to image_tag(@receive_user.image, class: "rounded-circle", size:"25x25"), controller: :users, action: :profile, id:@receive_user %>
        <%= @receive_user.name %>
    </div>
  </div>
</nav> -->

</div>

matching/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

matching/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Send user:</strong>
  <%= @message.send_user_id %>
</p>

<p>
  <strong>Receive user:</strong>
  <%= @message.receive_user_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>