matching/config/routes.rb
Rails.application.routes.draw do
  resources :block_lists
  resources :date_schedules
  resources :meet_requests
  root to: 'sessions#new'
  get 'messages/check'
  post 'messages/set_receive'
  get 'messages/set_receive'
  resources :messages
  get 'sessions/new'
  get 'match_requests/target_user_list'
  get 'users/:id/profile' => 'users#profile'
  resources :match_requests
  resources :users
  # post 'chat' => 'messages#index'
  post 'messages/index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy' #deleteの場合はmethod: :deleteが必要
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

matching/app/models/user.rb
class User < ApplicationRecord
# Login機能のため
has_secure_password
# MatchRequestを介してuser-userがn対nの関係
has_many :sent_match_requests, :class_name => MatchRequest, :foreign_key => :request_user_id
has_many :targeted_match_requests, :class_name => MatchRequest, :foreign_key => :target_user_id
# MeetRequestを介してuser-userがn対nの関係
has_many :sent_meet_requests, :class_name => MeetRequest, :foreign_key => :meet_request_user_id
has_many :targeted_meet_requests, :class_name => MeetRequest, :foreign_key => :meet_target_user_id
# Messageを介してuser-userがn対nの関係
has_many :send_message, :class_name => Message, :foreign_key => :send_user_id
has_many :receive_message, :class_name => Message, :foreign_key => :receive_user_id
# emailをdownscaleすることで確実に一致させる
before_save { self.email = email.downcase }
# バリデーション
validates :name, presence: true, length: { maximum: 50 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
# 画像アップロード用
mount_uploader :image, ImageUploader
mount_uploader :image2, ImageUploader0
mount_uploader :image3, ImageUploader0
mount_uploader :image4, ImageUploader0

  def matchers
      requester_ids = targeted_match_requests.pluck(:request_user_id)
          sent_match_requests
                .eager_load(:target_user)
                      .select { |r| requester_ids.include? r.target_user_id }
                            .map { |r| r.target_user }
  end

  def meet_matchers
      requester_ids = targeted_meet_requests.pluck(:meet_request_user_id)
          sent_meet_requests
                .eager_load(:meet_target_user)
                      .select { |r| requester_ids.include? r.meet_target_user_id }
                            .map { |r| r.meet_target_user }
  end

  # def meet_match?
  #   to_flag = MeetRequest.exists?(meet_request_user_id: params[:send_id], meet_target_user_id: params[:receive_id])
  #   from_flag = MeetRequest.exists?(meet_request_user_id: params[:receive_id], meet_target_user_id: params[:send_id])
  #   return to_flag && from_flag
  # end
end

matching/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:profile,:show, :edit, :update, :destroy, :index]
  # ログイン判定
  before_action :login_check, only: [:profile,:show, :edit, :update, :destroy,:index]
  # GET /users
  # GET /users.json
  def profile
  end

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end
  # GET /users/new
  def new
    @age_range = (18..99).to_a
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @access_id = params[:id]
    if @access_id.to_i != @current_user.id
      redirect_to match_requests_target_user_list_path
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
       redirect_to controller: "sessions", action:"new", notice:"ユーザの登録に成功しました"
    else
      redirect_to action: "new", notice:"有効な値を入力してください"
    end
    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: 'User was successfully created.' }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      redirect_to match_requests_target_user_list_path, notice:"プロフィールを更新しました。"
    end
    # respond_to do |format|
    #   if @user.update(user_params)
    #     format.html { redirect_to @user, notice: 'User was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @user }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @current_user = User.find_by(id: session[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :string, :image,:image2,:image3,:image4, :email, :password, :prof, :sex, :age, :place)
    end

    def login_check
      if session[:user_id] == nil
        redirect_to controller:'sessions',action:'new', notice:'ログインしてください'
      end
    end
end

matching/app/helpers/users_helper.rb
module UsersHelper
end

matching/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container-fluid col-8" style="background-color:white;padding:3%;box-shadow: 0px 0px 8px silver;">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class:"form-control" %>
  </div>
  <div class="field">
    <div class="row">
      <div class="col-6">
        <%= form.label '年齢' %><br>
        <%= form.select :age, @age_range, :selected => 18, class:"form-control" %><br>
        <span style="color:gray;">※後から変更できません</span>
      </div>
      <div class="col-6">
        <label>性別</label><br>
        <label><%= form.radio_button :sex, 0, :checked => "checked" %> 男性</label>
        <label><%= form.radio_button :sex, 1 %> 女性</label><br>
        <span style="color:gray;">※後から変更できません</span>
      </div>
    </div>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email,class:"form-control"%>
  </div>
  <!-- パスワードは認証の処理が必要 -->
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password,class:"form-control"%>
  </div>
  <p class="lead">画像を追加</p>
  <div class="row">
    <div class="container col-md-3">
      <div class="field" style="padding:2%">
        <!--onClickで画像タップが画像選択になる。idで同じところを探してる。-->
        <%= image_tag user.image, class:"rounded", style:"padding:2%",onClick:"$('#upfile').click()",id:"img_prev" %>
        <%= form.file_field :image,style:"display:none;", id:"upfile"%>
          <script type="text/javascript">
          $(function() {
            function readURL(input) {
              if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                  $('#img_prev').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
              }
            }

            $("#upfile").change(function(){
              $('#img_prev').removeClass('hidden');
              readURL(this);
            });
          });
          </script>
      </div>
    </div>
    <div class="container col-md-3">
      <div class="field" style="padding:2%">
          <%= image_tag user.image2, class:"rounded", style:"padding:2%",onClick:"$('#upfile2').click()",id:'img_prev2' %>
          <%= form.file_field :image2, style:"display:none;", id:"upfile2"%>
          <script type="text/javascript">
          $(function() {
            function readURL(input) {
              if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                  $('#img_prev2').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
              }
            }

            $("#upfile2").change(function(){
              $('#img_prev2').removeClass('hidden');
              readURL(this);
            });
          });
          </script>
      </div>
    </div>
    <div class="container col-md-3">
      <div class="field" style="padding:2%">
          <%= image_tag user.image3, class:"rounded", style:"padding:2%", onClick:"$('#upfile3').click()",id:"img_prev3"%>
          <%= form.file_field :image3, style:"display:none;", id:"upfile3" %>
          <script type="text/javascript">
          $(function() {
            function readURL(input) {
              if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                  $('#img_prev3').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
              }
            }

            $("#upfile3").change(function(){
              $('#img_prev3').removeClass('hidden');
              readURL(this);
            });
          });
          </script>
      </div>
    </div>
    <div class="container col-md-3">
      <div class="field" style="padding:2%">
        <%= image_tag user.image4, class:"rounded", style:"padding:2%", onClick:"$('#upfile4').click()",id:"img_prev4"%>
        <%= form.file_field :image4, style:"display:none;", id:"upfile4"%>
        <script type="text/javascript">
        $(function() {
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();

              reader.onload = function (e) {
                $('#img_prev4').attr('src', e.target.result);
              }
              reader.readAsDataURL(input.files[0]);
            }
          }

          $("#upfile4").change(function(){
            $('#img_prev4').removeClass('hidden');
            readURL(this);
          });
        });
        </script>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label for="self-introduciton">プロフィール</label>
    <%= form.text_area :prof, class: "form-control", rows: "3"%>
  </div>


  <div class="actions">
    <%= link_to 'ホームに戻る',sessions_new_path, class:"btn btn-primary", align:"left"%>
    <%= form.submit '利用規約に同意して登録',class:"btn btn-success", align:"right"%>
  </div>

<% end %>

matching/app/views/users/edit.html.erb
<!-- <%= @access_id %><%= @current_user.id %><%= @access_id.to_i==@current_user.id %> -->
<h1 style="margin-top:3%;"></h1>
<%= form_with(model: @user) do |form| %>
<div class="container-fluid col-md-8" style="background-color:white;padding:3%;box-shadow: 0px 0px 8px silver;">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email,class:"form-control"%>
  </div>
  <!-- パスワードは認証の処理が必要 -->
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password,class:"form-control"%>
  </div>
  <p class="lead">現在の画像</p>
  <div class="row">
    <div class="container col-3">
      <div class="field" style="padding:2%">
        <%= image_tag @user.image, class:"rounded", style:"padding:2%",onClick:"$('#upfile').click()",id:"img_prev" %>
        <%= form.file_field :image,style:"display:none;", id:"upfile"%>
          <script type="text/javascript">
          $(function() {
            function readURL(input) {
              if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                  $('#img_prev').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
              }
            }

            $("#upfile").change(function(){
              $('#img_prev').removeClass('hidden');
              readURL(this);
            });
          });
          </script>
      </div>
    </div>
    <div class="container col-3">
      <div class="field" style="padding:2%">
        <%= image_tag @user.image2, class:"rounded", style:"padding:2%",onClick:"$('#upfile2').click()",id:'img_prev2' %>
        <%= form.file_field :image2, style:"display:none;", id:"upfile2"%>
        <script type="text/javascript">
        $(function() {
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();

              reader.onload = function (e) {
                $('#img_prev2').attr('src', e.target.result);
              }
              reader.readAsDataURL(input.files[0]);
            }
          }

          $("#upfile2").change(function(){
            $('#img_prev2').removeClass('hidden');
            readURL(this);
          });
        });
        </script>
      </div>
    </div>
    <div class="container col-3">
      <div class="field" style="padding:2%">
        <%= image_tag @user.image3, class:"rounded", style:"padding:2%", onClick:"$('#upfile3').click()",id:"img_prev3"%>
        <%= form.file_field :image3, style:"display:none;", id:"upfile3" %>
        <script type="text/javascript">
        $(function() {
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();

              reader.onload = function (e) {
                $('#img_prev3').attr('src', e.target.result);
              }
              reader.readAsDataURL(input.files[0]);
            }
          }

          $("#upfile3").change(function(){
            $('#img_prev3').removeClass('hidden');
            readURL(this);
          });
        });
        </script>
      </div>
    </div>
    <div class="container col-3">
      <div class="field" style="padding:2%">
        <%= image_tag @user.image4, class:"rounded", style:"padding:2%", onClick:"$('#upfile4').click()",id:"img_prev4"%>
        <%= form.file_field :image4, style:"display:none;", id:"upfile4"%>
        <script type="text/javascript">
        $(function() {
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();

              reader.onload = function (e) {
                $('#img_prev4').attr('src', e.target.result);
              }
              reader.readAsDataURL(input.files[0]);
            }
          }

          $("#upfile4").change(function(){
            $('#img_prev4').removeClass('hidden');
            readURL(this);
          });
        });
        </script>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label for="self-introduciton">プロフィール</label>
    <%= form.text_area :prof, class: "form-control", rows: "3"%>
  </div>

  <div class="actions" align="right">
    <%= form.submit '更新',class:"btn btn-primary"%>
  </div>

</div>
<% end %>

matching/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

matching/app/views/users/new.html.erb
<h1 style="margin-top:3%;"></h1>

<%= render 'form', user: @user %>

<!-- <%= link_to 'Back', users_path %> -->

matching/app/views/users/profile.html.erb
<p id="notice"><%= notice %></p>
<!-- <p style="color:Red"><%= @current_user.name %>_<%= @current_user.id %>でログイン中</p> -->
<div class="container col-6 profile_card">
<div id="profile-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">

  <!-- 何枚目かの画像かを表すインディケーター -->
  <ol class="carousel-indicators">
    <li data-target="#profile-carousel" data-slide-to="0" class="active"></li>
    <% if @user.image2 %><li data-target="#profile-carousel" data-slide-to="1" class=""></li><% end %>
    <% if @user.image3 %><li data-target="#profile-carousel" data-slide-to="2" class=""></li><% end %>
  </ol>

  <!-- 実際の画像の表示処理 -->
  <div class="carousel-inner">
    <div class="carousel-item active">    <!-- activeをつけたものがページ表示時に表示される -->
      <%= image_tag @user.image, class: "d-block w-120", alt:"First slide"%>
      <!-- <p><%= @user.name %></p> -->
    </div>
    <% if @user.image2 %>
      <div class="carousel-item">
        <%= image_tag @user.image2, class: "d-block w-100", alt:"Second slide"%>
        <!-- <p><%= @user.name %></p> -->
      </div>
    <% end %>
    <% if @user.image3 %>
      <div class="carousel-item">
        <%= image_tag @user.image3, class: "d-block w-100", alt:"Third slide"%>
        <!-- <p><%= @user.name %></p> -->
      </div>
    <% end %>
  </div>

  <!-- 前の画像へ戻るための矢印ポインタ -->
  <a class="carousel-control-prev" href="#profile-carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#profile-carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

  <div class="name">
    <%= @user.name %>,
    <% if @user.sex == 0%><%= image_tag 'man.svg', size:"20x20"%><%else%><%= image_tag 'woman.svg',size:"20x20"%><%end%>,
    <% if @user.age %><%= @user.age %><%else%>未設定<%end%>
  </div>
  <div class="box26">
    <span class="box-title">プロフィール</span>
    <p>
      <% if @user.prof.length > 0 %>
        <%= @user.prof %>
      <% else %>
        <span style="color:silver;">プロフィールはありません。</p>
      <% end %>
    </p>
  </div>

  <!-- <%= link_to 'Back', users_path %> -->
</div>
<%= link_to '戻る', {controller: :match_requests, action: :target_user_list}, class: "btn btn-primary" %>
<br><br><br><br>

matching/app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
  <h1></h1>
  <!-- <div class = "row"> -->
    <!-- <div class="container col-md-4">
    </div> -->
    <div class="container col-md-6 col-md-offset-3">
      <strong>マッチした相手にメッセージを送る</strong><br>
      <table class="newest_message" style="width:100%">
        <% @user.matchers.each do |matcher| %>
          <tr>
            <th><%= link_to image_tag(matcher.image,class:'rounded-circle',size:"40x40"), controller: :users, action: :profile, id:matcher %></th>
            <td><%= matcher.name %></td>
            <% newest_message = Message.where(send_user_id:@current_user,receive_user_id:matcher).or(Message.where(send_user_id:matcher,receive_user_id:@current_user)).last%>
            <td>
              <% if newest_message%>
                <%= link_to newest_message.body.truncate(20), messages_path(receive_id: matcher.id, send_id: @user.id), style:"display:block; width:100%; height:100%; padding:10px; color:#c0c0c0; text-decoration: none;"%>
              <% else %>
                <%= link_to ' ', messages_path(receive_id: matcher.id, send_id: @user.id), style:"display:block; width:100%; height:100%; padding:10px; color:#c0c0c0; text-decoration: none;"%>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  <!-- <div class="container col-md-4">
  </div> -->
  <!-- </div> -->